//
// Created by Mykyta Maliarenko on 15.05.2020.
//

#ifndef EXAMTASKSBUILDER_GENERATE_EXAM_PAPERS_CONTROLLER_H
#define EXAMTASKSBUILDER_GENERATE_EXAM_PAPERS_CONTROLLER_H

int showGenerateExamPapersDialog();

#endif //EXAMTASKSBUILDER_GENERATE_EXAM_PAPERS_CONTROLLER_H
