//
// Created by Mykyta Maliarenko on 16.04.2020.
//

#ifndef EXAMTASKSBUILDER_MAIN_CONTROLLER_H
#define EXAMTASKSBUILDER_MAIN_CONTROLLER_H

int startMainWindow();

#endif //EXAMTASKSBUILDER_MAIN_CONTROLLER_H
