//
// Created by Mykyta Maliarenko on 17.04.2020.
//

const int EVENT_MAIN_WINDOW_ADD_QUESTION = 0;

const int EVENT_ADD_QUESTION_WINDOW_RESULT = 1;

const int EVENT_MAIN_WINDOW_GENERATE_EXAM_PAPERS = 2;

const int EVENT_MAIN_WINDOW_GENERATE_EXAM_PAPERS_RESULT = 3;