//
// Created by Mykyta Maliarenko on 17.04.2020.
//

const int EVENT_MAIN_WINDOW_ADD_QUESTION = 0;

const int EVENT_ADD_QUESTION_WINDOW_RESULT = 1;

const int EVENT_MAIN_WINDOW_GENERATE_EXAM_PAPERS = 2;

const int EVENT_GENERATE_EXAM_PAPERS_WINDOW_RESULT = 3;

const int EVENT_MAIN_WINDOW_FILE_SYSTEM_SAVE = 4;

const int EVENT_MAIN_WINDOW_FILE_SYSTEM_LOAD = 5;

const int EVENT_MAIN_WINDOW_EXPORT_QUESTIONS = 1005;//Happy birthday Kate(I love you)

const int EVENT_MAIN_WINDOW_EXPORT_EXAM_PAPERS = 2907;// Happy birthday Me