//
// Created by Mykyta Maliarenko on 28.03.2020.
//

#ifndef EXAMTASKSBUILDER_EVENTS_H
#define EXAMTASKSBUILDER_EVENTS_H

const int EVENT_MAIN_WINDOW_ADD_QUESTION;

const int EVENT_ADD_QUESTION_WINDOW_RESULT;

const int EVENT_MAIN_WINDOW_GENERATE_EXAM_PAPERS;

const int EVENT_MAIN_WINDOW_GENERATE_EXAM_PAPERS_RESULT;

#endif //EXAMTASKSBUILDER_EVENTS_H
