//
// Created by Mykyta Maliarenko on 28.03.2020.
//

#ifndef EXAMTASKSBUILDER_EVENTS_H
#define EXAMTASKSBUILDER_EVENTS_H

const int EVENT_MAIN_WINDOW_ADD_QUESTION = 0;

const int EVENT_MAIN_WINDOW_GENERATE_EXAM_PAPERS = 1;


#endif //EXAMTASKSBUILDER_EVENTS_H
