//
// Created by Mykyta Maliarenko on 28.03.2020.
//

#ifndef EXAMTASKSBUILDER_EVENTS_H
#define EXAMTASKSBUILDER_EVENTS_H

const int EVENT_MAIN_WINDOW_ADD_QUESTION;

const int EVENT_ADD_QUESTION_WINDOW_RESULT;

const int EVENT_MAIN_WINDOW_GENERATE_EXAM_PAPERS;

const int EVENT_GENERATE_EXAM_PAPERS_WINDOW_RESULT;

const int EVENT_MAIN_WINDOW_FILE_SYSTEM_SAVE;

const int EVENT_MAIN_WINDOW_FILE_SYSTEM_LOAD;

const int EVENT_MAIN_WINDOW_EXPORT_QUESTIONS;

const int EVENT_MAIN_WINDOW_EXPORT_EXAM_PAPERS;


#endif //EXAMTASKSBUILDER_EVENTS_H
