//
// Created by Mykyta Maliarenko on 27.03.2020.
//

#ifndef EXAMTASKSBUILDER_STORAGE_FIELDS_H
#define EXAMTASKSBUILDER_STORAGE_FIELDS_H

const int STORAGE_QUESTIONS;

const int STORAGE_EXAM_PAPERS;

#endif //EXAMTASKSBUILDER_STORAGE_FIELDS_H
